2011/04/21 12:49:55 [crit] 7659#0: *1 connect() to unix:/home/vladka/hhspace/logs/django-server.sock failed (13: Permission denied) while connecting to upstream, client: 10.0.2.15, server: h-hspace.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/vladka/hhspace/logs/django-server.sock:", host: "h-hspace.loc"
2011/04/21 12:52:09 [crit] 7766#0: *1 connect() to unix:/home/vladka/hhspace/logs/django-server.sock failed (13: Permission denied) while connecting to upstream, client: 10.0.2.15, server: h-hspace.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/vladka/hhspace/logs/django-server.sock:", host: "h-hspace.loc"
2011/04/21 12:56:31 [crit] 7957#0: *1 connect() to unix:/home/vladka/hhspace/logs/django-server.sock failed (13: Permission denied) while connecting to upstream, client: 10.0.2.15, server: h-hspace.loc, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/home/vladka/hhspace/logs/django-server.sock:", host: "h-hspace.loc"
